### ISSUE TITLE
Missing type for `responseErrorHandler`

### ISSUE THREAD

**Issue by timmyichen** [drodriques/express-response-errors#34]
In a TS file, attempting to import `responseErrorHandler` like so:

```
import { responseErrorHandler } from 'express-response-errors';
```

Throws a TS error:

```
Module '"../node_modules/express-response-errors/types"' has no exported member 'responseErrorHandler'.ts(2305)
```

We can see that [index.d.ts](https://github.com/drodriques/express-response-errors/blob/master/types/index.d.ts) is missing the type definition for the middleware.

Any chance it could be added?  If you'd like, I can take a stab at the PR as well.

**Comment by drodriques** [comment]
Hi, will try to have this resolved today, thanks for your feedback.

**Comment by drodriques** [comment]
Issue should now be resolved, PRs are welcome :)

**Comment by timmyichen** [comment]
Thanks for the fast response!  Much appreciated :)
